name: math_example
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  path:

#dev_dependencies:
#  pedantic: ^1.9.0
