name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  utils_example:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: utils_example
    
    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1

      - name: Build C library
        run: |
          cd utilslib
          cmake .
          make

      - name: Install Dart dependencies
        run: dart pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      - name: Run app
        run: dart run
